area1_x: -0.524
area1_y: -0.341
area1_orientation: 3.020

area2_x: -1.866
area2_y: -1.223
area2_orientation: -1.704

area3_x: -2.162
area3_y: -0.778
area3_orientation: 2.936

area4_x: -1.967
area4_y: 0.227
area4_orientation: 3.049

area5_x: -1.575
area5_y: 0.855
area5_orientation: 1.518

casa_x: 0.338
casa_y: -0.221
casa_orientation: 3.035

deposito_x: -0.049
deposito_y: 1.335
deposito_orientation: 0.042

pedido_x: -0.498
pedido_y: -1.924
pedido_orientation: -0.095
